djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from core.views import TestView, LeadTestView, PostCreateAPI, PostGetAPI
from rest_framework.authtoken.views import obtain_auth_token
from leads.views import landing_page, LandingTemplateView, SignupView

urlpatterns = [
    path('', LandingTemplateView.as_view(), name='landing-page'),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('core/', TestView.as_view(), name='test'),
    path('core/get/', PostGetAPI.as_view(), name='get-post-api-test'),
    path('core/post/', PostCreateAPI.as_view(), name='create-post-api-test'),
    path('lead/test/', LeadTestView.as_view(), name='lead-api'),
    path('user/token/', obtain_auth_token, name='obtain-token'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (leads_list, lead_details, create_lead,
                    lead_update, lead_delete, LeadListView, LeadDetailView, LeadDeleteView, LeadCreateView)

app_name = 'leads'
urlpatterns = [
    path('', LeadListView.as_view(), name='leads-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-details'),
    path('<int:pk>/update/', lead_update, name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model

# return the defualt user
# User1 = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    agent_user = models.ForeignKey('User', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey('Agent', on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name


class UserProfile(models.Model):
    user = models.OneToOneField('User', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class User(AbstractUser):
    pass


class Agent(models.Model):
    user = models.OneToOneField("User", on_delete=models.CASCADE)
    orgnizatino = models.ForeignKey('UserProfile', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Lead, User

User = get_user_model()


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        )


class LeadForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    age = forms.IntegerField()


class CustomUserCreation(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

leads/views.py
from django.shortcuts import render, redirect, reverse
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views import generic
from django.views.generic import TemplateView, ListView, DetailView, DeleteView, CreateView, UpdateView
from .models import Lead, User, Agent
from .forms import LeadForm, LeadModelForm, CustomUserCreation

# CRUD+L Create, Retrieve, Update, Delete, and List


class SignupView(LoginRequiredMixin, generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreation

    def get_success_url(self):
        # Reverse takes works by the URL name convention
        return reverse('leads:leads-list')


class LandingTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'landing.html'


def landing_page(request):
    return render(request, 'landing.html')


class LeadListView(LoginRequiredMixin, ListView):
    template_name = 'leads/leads_list.html'
    # This must be set to bring all data pass it to the context
    queryset = Lead.objects.all()
    # This for the context goes to the Template HTML file
    context_object_name = "leads"


def leads_list(request):
    leads = Lead.objects.all()
    # return render(request,'leads/home_page.html')
    print(leads)
    context = {
        "leads": leads
    }
    return render(request, 'leads/leads_list.html', context)


class LeadDetailView(LoginRequiredMixin, DetailView):
    template_name = 'leads/lead_details.html'
    queryset = Lead.objects.all()
    context_object_name = 'lead'


def lead_details(request, pk):
    print(pk)
    lead = Lead.objects.get(id=pk)
    print(lead)
    context = {
        "lead": lead
    }

    return render(request, 'leads/lead_details.html', context)


class LeadCreateView(LoginRequiredMixin, CreateView):
    template_name = 'leads/lead_create.html'
    form_class = LeadModelForm

    def get_success_url(self):
        print('done')
        # Reverse takes works by the URL name convention
        return reverse('leads:leads-list')

    def form_valid(self, form):
        print('email has been sent')
        send_mail(subject='This is just for a new lead created sub',
                  message='please notes we had created your acount',
                  from_email='test@test.com',
                  recipient_list=['whilist@test.com'])

        return super(LeadCreateView, self).form_valid(form)


def create_lead(request):
    form = LeadModelForm()
    if request.method == 'POST':
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()  # Create object base on the model defined

            return redirect('/leads')
    context = {
        "form": form
    }
    return render(request, 'leads/lead_create.html', context)


class LeadUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'leads/lead_update.html'
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse('leads:lead-update')


def lead_update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == 'POST':
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()  # related to ModelForm will save the data auto

            return redirect('/leads')
    context = {
        'form': form,
        'lead': lead
    }
    return render(request, 'leads/lead_update.html', context)


class LeadDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'leads/lead_delete.html'
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse('leads:leads-list')


def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()

    return redirect('/leads')
# def create_lead(request):
#     form = LeadModelForm()
#     if request.method == 'POST':
#         form = LeadModelForm(request.POST)
#         if form.is_valid():
#             form.save() # Create object base on the model defined

#             return redirect('/leads')
#     context = {
#         "form" : form
#     }
#     return render(request,'create_lead.html',context)

leads/templates/leads/lead_create.html
{% extends 'base.html' %} {% block content %}
<strong>create lead page</strong>
<a href="{% url 'leads:leads-list' %}">Go back to leads </a>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">submit</button>

  {% endblock content %}
</form>

leads/templates/leads/lead_delete.html
{% extends 'base.html' %} {% block content %}
<strong>Are you sure you want to delete this lead</strong>
<a href="{% url 'leads:leads-list' %}">Go back to leads </a>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">submit</button>

  {% endblock content %}
</form>

leads/templates/leads/lead_details.html
{% extends 'base.html' %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ lead.first_name}} {{ lead.last_name }}
        </h1>
        <div class="flex mb-4">
          <a
            class="
              flex-grow
              text-indigo-500
              border-b-2 border-indigo-500
              py-2
              text-lg
              px-1
            "
            >Description</a
          >
          <a
            href="{% url 'leads:lead-update' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Update</a
          >
          <a
            href="{% url 'leads:lead-delete' lead.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Delete</a
          >
        </div>
        <p class="leading-relaxed mb-4">
          Fam locavore kickstarter distillery. Mixtape chillwave tumeric
          sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps
          cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine
          tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{lead.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Agent</span>
          <span class="ml-auto text-gray-900">{{lead.agent}}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Riyadh</span>
        </div>
        <div class="flex">
          <button
            class="
              flex
              ml-auto
              text-white
              bg-indigo-500
              border-0
              py-2
              px-6
              focus:outline-none
              hover:bg-indigo-600
              rounded
            "
          >
            Button
          </button>
          <button
            class="
              rounded-full
              w-10
              h-10
              bg-gray-200
              p-0
              border-0
              inline-flex
              items-center
              justify-center
              text-gray-500
              ml-4
            "
          >
            <svg
              fill="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-5 h-5"
              viewBox="0 0 24 24"
            >
              <path
                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"
              ></path>
            </svg>
          </button>
        </div>
      </div>
      <img
        alt="ecommerce"
        class="
          lg:w-1/2
          w-full
          lg:h-auto
          h-64
          object-cover object-center
          rounded
        "
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/lead_update.html
<!DOCTYPE html>
<html>
  <head>
    <title>Qanateer | store</title>
    <meta
      name="description"
      content="our store is the best in the their scope"
    />
    <meta charset="utf-8" />
    <meta name="robots" content="index, follow" />
    <link rel="icon" href="/img/presentation_icon_194170.png" />
    <link rel="stylesheet" href="/style.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style></style>
  </head>
  <body>
    <strong>Here is the lead update page{{ lead.first_name }} </strong>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">submit</button>
    </form>
  </body>
</html>

leads/templates/leads/leads_list.html
{% extends 'base.html' %} {% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <a href='{% url "leads:lead-create" %}'>create a new lead</a>
    <div class="flex flex-wrap -m-4">
      {% for lead in leads %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="
            flex
            border-2
            rounded-lg
            border-gray-200 border-opacity-50
            p-8
            sm:flex-row
            flex-col
          "
        >
          <div
            class="
              w-16
              h-16
              sm:mr-8 sm:mb-0
              mb-4
              inline-flex
              items-center
              justify-center
              rounded-full
              bg-indigo-100
              text-indigo-500
              flex-shrink-0
            "
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{ lead.first_name }} {{ lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">
              Blue bottle crucifix vinyl post-ironic four dollar toast vegan
              taxidermy. Gastropub indxgo juice poutine.
            </p>
            <a
              href="{% url 'leads:lead-details' lead.pk %}"
              class="mt-3 text-indigo-500 inline-flex items-center"
              >View This Lead
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}