agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView
app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agents-list'),
    path('create/', AgentCreateView.as_view(), name='create-agent'),
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from core.views import TestView, LeadTestView, PostCreateAPI, PostGetAPI
from rest_framework.authtoken.views import obtain_auth_token
from leads.views import landing_page, LandingTemplateView, SignupView

urlpatterns = [
    path('', LandingTemplateView.as_view(), name='landing-page'),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('core/', TestView.as_view(), name='test'),
    path('core/get/', PostGetAPI.as_view(), name='get-post-api-test'),
    path('core/post/', PostCreateAPI.as_view(), name='create-post-api-test'),
    path('lead/test/', LeadTestView.as_view(), name='lead-api'),
    path('user/token/', obtain_auth_token, name='obtain-token'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django.forms import fields, forms, ModelForm, models
from leads.models import Agent


class AgentModelForm(ModelForm):
    class Meta:
        model = Agent
        fields = (
            'user',
        )

agents/views.py
from django.views import generic
from django.shortcuts import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent, Lead
from .forms import AgentModelForm


class AgentListView(LoginRequiredMixin, generic.ListView):
    template_name = 'agents/agents_list.html'

    def get_queryset(self):
        return Agent.objects.all()


class AgentCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'agents/agent_create.html'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agents-list')

    def form_valid(self, form):
        agent = form.save(commit=False)
        agent.orgnizatino = self.request.user.userprofile
        agent.save()
        return super(AgentCreateView, self).form_valid(form)

agents/templates/agents/agent_create.html
{% extends 'base.html' %} {% block content %}
<strong>create agent page</strong>
<a href="{% url 'agents:agents-list' %}">Go back to agents </a>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">submit</button>

  {% endblock content %}
</form>

agents/templates/agents/agents_list.html
{% extends "base.html" %} {% block content %}
<h1>Here our agents page</h1>

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <a href='{% url "agents:create-agent" %}'>create a new agent</a>
      <div class="flex flex-wrap -m-4">
        {% for agent in object_list %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div
            class="
              flex
              border-2
              rounded-lg
              border-gray-200 border-opacity-50
              p-8
              sm:flex-row
              flex-col
            "
          >
            <div
              class="
                w-16
                h-16
                sm:mr-8 sm:mb-0
                mb-4
                inline-flex
                items-center
                justify-center
                rounded-full
                bg-indigo-100
                text-indigo-500
                flex-shrink-0
              "
            >
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-8 h-8"
                viewBox="0 0 24 24"
              >
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                {{ agent.user.first_name }}
              </h2>
              <p class="leading-relaxed text-base">
                Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                taxidermy. Gastropub indxgo juice poutine.
              </p>
              <a
                href="#"
                class="mt-3 text-indigo-500 inline-flex items-center"
                >View This Lead
                <svg
                  fill="none"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  class="w-4 h-4 ml-2"
                  viewBox="0 0 24 24"
                >
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock content %}