djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from core.views import TestView, LeadTestView, PostCreateAPI, PostGetAPI
from rest_framework.authtoken.views import obtain_auth_token
from leads.views import landing_page, LandingTemplateView, SignupView

urlpatterns = [
    path('', LandingTemplateView.as_view(), name='landing-page'),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('core/', TestView.as_view(), name='test'),
    path('core/get/', PostGetAPI.as_view(), name='get-post-api-test'),
    path('core/post/', PostCreateAPI.as_view(), name='create-post-api-test'),
    path('lead/test/', LeadTestView.as_view(), name='lead-api'),
    path('user/token/', obtain_auth_token, name='obtain-token'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (leads_list, lead_details, create_lead,
                    lead_update, lead_delete, LeadListView, LeadDetailView, LeadDeleteView, LeadCreateView)

app_name = 'leads'
urlpatterns = [
    path('', LeadListView.as_view(), name='leads-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-details'),
    path('<int:pk>/update/', lead_update, name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Qanateer | store</title>
    <meta
      name="description"
      content="our store is the best in the their scope"
    />
    <meta charset="utf-8" />
    <meta name="robots" content="index, follow" />
    <link rel="icon" href="/img/presentation_icon_194170.png" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    {% include "navbar.html" %} {% block content %} {% endblock content %}
  </body>
</html>

templates/landing.html
{% extends 'base.html' %} {% block content %}
<section class="text-gray-600 body-font">
  <div
    class="
      container
      mx-auto
      flex
      px-5
      py-24
      items-center
      justify-center
      flex-col
    "
  >
    <img
      class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded"
      alt="hero"
      src="https://dummyimage.com/720x600"
    />
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"
      >
        CRM build with Django
      </h1>
      <p class="mb-8 leading-relaxed">This CRM helps manage your leads</p>
      <div class="flex justify-center">
        <button
          class="
            inline-flex
            text-white
            bg-indigo-500
            border-0
            py-2
            px-6
            focus:outline-none
            hover:bg-indigo-600
            rounded
            text-lg
          "
        >
          Button
        </button>
        <button
          class="
            ml-4
            inline-flex
            text-gray-700
            bg-gray-100
            border-0
            py-2
            px-6
            focus:outline-none
            hover:bg-gray-200
            rounded
            text-lg
          "
        >
          Button
        </button>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div
    class="
      container
      mx-auto
      flex flex-wrap
      p-5
      flex-col
      md:flex-row
      items-center
    "
  >
    <a
      class="
        flex
        title-font
        font-medium
        items-center
        text-gray-900
        mb-4
        md:mb-0
      "
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
        viewBox="0 0 24 24"
      >
        <path
          d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
        ></path>
      </svg>
      <span class="ml-3 text-xl">DJ CRM</span>
    </a>
    <nav
      class="md:ml-auto flex flex-wrap items-center text-base justify-center"
    >
      <a href="{%url 'leads:leads-list' %}" class="mr-5 hover:text-gray-900"
        >Leads</a
      >
      {% if not request.user.is_authenticated %}
      <a href='{% url "signup" %}' class="mr-5 hover:text-gray-900">Sign Up</a>
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %} Y ou are logged in as
    :{{request.user.username}}
    <a
      href="{% url 'logout' %}"
      class="
        inline-flex
        items-center
        bg-gray-100
        border-0
        py-1
        px-3
        focus:outline-none
        hover:bg-gray-200
        rounded
        text-base
        mt-4
        md:mt-0
      "
    >
      Logout

      <svg
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-4 h-4 ml-1"
        viewBox="0 0 24 24"
      >
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% else%}
    <a
      href="{% url 'login' %}"
      class="
        inline-flex
        items-center
        bg-gray-100
        border-0
        py-1
        px-3
        focus:outline-none
        hover:bg-gray-200
        rounded
        text-base
        mt-4
        md:mt-0
      "
    >
      Login

      <svg
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-4 h-4 ml-1"
        viewBox="0 0 24 24"
      >
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
  </div>
  {% endif %}
</header>

templates/scripts.html
{% load static %}
<script src="{% static 'js/main.js'%}"></script>